		.MODEL LARGE
		.STACK 64
		.DATA
CUMLE		DB	100 DUP(?)
KELIME_YAZDIR	DB	100 DUP(?)
RANDOM_KEL	DB	100 DUP(?)
		.CODE
MAIN		PROC	FAR		
		MOV	AX,@DATA	
		MOV	DS,AX		
		MOV	DI,OFFSET CUMLE
		MOV	CX,03h
		PUSH	CX
		SUB	BL,BL
VERÝ_AL:	MOV	AH,01H
		INT	21H
		MOV	[DI],AL
		INC	DI
		CMP	AL,13
		JNE	VERÝ_AL
		MOV	DI,OFFSET CUMLE
		MOV	SI,OFFSET KELIME_YAZDIR
		MOV	[SI],DI
		INC	DI
		INC	SI
KEL_BAS_AL:	MOV	AL,[DI]
		INC	DI
		CMP	AL,13
		JE	ENTER_EKLE
		CMP	AL,' '
		JNE	KEL_BAS_AL
		INC	BL
		MOV	BH,BL
		MOV	DX,DI
		MOV	[SI],DX
		INC	SI
		JMP	KEL_BAS_AL
ENTER_EKLE:	INC	BH
		MOV	AL,13
		MOV	[SI],AL
		MOV	DI,OFFSET RANDOM_KEL
RAND_KEL:	MOV	AH,2Ch
		INT	21h
		MOV	SI,OFFSET KELIME_YAZDIR
		POP	CX
		SHR	DL,CL
		PUSH	CX
		AND	DL,BL
		SUB	DH,DH
		ADD	SI,DX
		MOV	AL,[SI]
		MOV	[DI],AL
		INC	DI
SON_BUL:	SUB	AX,AX
		INC	SI
		MOV	AL,[SI]
		DEC	SI
		MOV	[SI],AL
		INC	SI
		CMP	AL,13
		JNE	SON_BUL
		DEC	BL
		DEC	BH
		CMP	BH,0h
		JNE	RAND_KEL
		MOV	DH,13
		MOV	[DI],DH
		MOV	DI,OFFSET RANDOM_KEL
YAZ_DIGER_KEL:	MOV	SI,OFFSET CUMLE
		SUB	AX,AX
		MOV	AL,[DI]
		SUB	AH,AH
		ADD	SI,AX
		MOV	DH,13
		CMP	[DI],DH
		JE	TEKRAR_YAP
		INC	DI
YAZ:		SUB	DX,DX
		MOV	DL,[SI]
		INC	SI
		CMP	DL,13
		JE	BOSLUK_KOY
		MOV	AH,02h
		INT	21h
		CMP	AL,' '
		JE	YAZ_DIGER_KEL
		JMP	YAZ
BASA_DON:	JMP	KEL_BAS_AL
BOSLUK_KOY:	MOV	DL,' '
		MOV	AH,02h
		INT	21h
		JMP	YAZ_DIGER_KEL
TEKRAR_YAP:	POP	CX
		DEC	CX
		PUSH 	CX
		MOV	DI,OFFSET CUMLE
		MOV	SI,OFFSET KELIME_YAZDIR
		MOV	[SI],DI
		INC	DI
		INC	SI
		SUB	BX,BX
		CMP	CX,0
		JNE	BASA_DON
		MOV	AH,4CH		
		INT	21H		
MAIN		ENDP			
		END	MAIN		
		